### ISSUE TITLE
Matriz Políticas de Despacho

### ISSUE THREAD

**Issue by lliempi** [jesuspoleo18/seichile#13]
Carlos debe enviar matriz

![image](https://user-images.githubusercontent.com/10941521/40132048-b145abfc-5909-11e8-9bd1-9cf289a5c020.png)

**Comment by jesuspoleo18** [comment]
@carlosmardonese mano, me avisas cuando subas ésto o si lo puedes cargar por acá, slack o enviarlo al correo para hacerlo, 💋 .

**Comment by carlosmardonese** [comment]
Va la Tabla:

![image](https://user-images.githubusercontent.com/37640790/40143652-04d05c16-592a-11e8-89e1-636ee0e6211b.png)

Región | R.M | XV | I | II | III | IV | V | VI | VII | VIII | IX | XIV | X | XI | XII
Costo | 2900 | 7900 | 7900 | 5900 | 5900 | 2900 | 2900 | 2900 | 2900 | 2900 | 5900 | 5900 | 7900 | 7900 | 7900
