### ISSUE TITLE
Revisión Interna 15/05 - Atributos FDP

### ISSUE THREAD

**Issue by lliempi** [jesuspoleo18/seichile#7]
En ficha de producto eliminar títulos "Atributos Raíz" y "Atributos"
![captura-sei7](https://user-images.githubusercontent.com/10941521/40064861-67e7e154-582e-11e8-86b7-092eb104ba55.JPG)

**Comment by jesuspoleo18** [comment]
@lliempi y los dejamos sin titulo?
